#!/usr/bin/env node
/**
 * Generates supabase/schools_seed_ca_full.sql from the California Department
 * of Education's "Public Schools and Districts" directory (pubschls.txt):
 *   https://www.cde.ca.gov/schooldirectory/report?rid=dl1&tp=txt
 *
 * This script only reads a local file and writes a local .sql file — it
 * never connects to Supabase. The generated file is meant to be reviewed and
 * run manually in the Supabase SQL editor, same as every other migration in
 * this project.
 *
 * Usage:
 *   node scripts/import_ca_schools.js [path-to-pubschls.txt]
 *
 * Defaults to scripts/data/pubschls.txt if no path is given.
 */

const fs = require('fs');
const path = require('path');

const inputPath = process.argv[2] || path.join(__dirname, 'data', 'pubschls.txt');
const outputPath = path.join(__dirname, '..', 'supabase', 'schools_seed_ca_full.sql');
const BATCH_SIZE = 500;

if (!fs.existsSync(inputPath)) {
  console.error(`Input file not found: ${inputPath}`);
  console.error('Download it from https://www.cde.ca.gov/schooldirectory/report?rid=dl1&tp=txt');
  process.exit(1);
}

// Postgres string literal escaping: double any single quote. Real school
// names in this file do contain apostrophes (e.g. "O'Hara Park Middle"),
// so this isn't a theoretical concern.
function escapeSqlString(value) {
  return value.replace(/'/g, "''");
}

// CDE uses the literal string "No Data" for any field it doesn't have —
// treated as SQL NULL, same as an empty string.
function sqlLiteral(value) {
  if (!value || value === 'No Data') return 'null';
  return `'${escapeSqlString(value)}'`;
}

const raw = fs.readFileSync(inputPath, 'utf8');
const lines = raw.split(/\r?\n/).filter((line) => line.length > 0);

if (lines.length < 2) {
  console.error('Input file has no data rows.');
  process.exit(1);
}

const header = lines[0].split('\t');
const col = {};
header.forEach((name, i) => {
  col[name] = i;
});

const REQUIRED_COLUMNS = ['NCESDist', 'NCESSchool', 'StatusType', 'School', 'City', 'State', 'District'];
for (const name of REQUIRED_COLUMNS) {
  if (!(name in col)) {
    console.error(`Expected column "${name}" not found in the file header — the CDE file format may have changed.`);
    process.exit(1);
  }
}

const rows = [];
const seenIds = new Set();
let skippedNotActive = 0;
let skippedNoSchoolId = 0;
let skippedDuplicate = 0;
let skippedNoName = 0;

for (let i = 1; i < lines.length; i++) {
  const fields = lines[i].split('\t');
  const status = fields[col.StatusType];
  const distId = fields[col.NCESDist];
  const schoolId = fields[col.NCESSchool];
  const name = fields[col.School];

  // Active only — excludes Closed, Merged, and Pending records.
  if (status !== 'Active') {
    skippedNotActive++;
    continue;
  }

  // A valid school-level NCES id needs both a 7-digit district id and a
  // 5-digit school id. County-office/district-admin rows report NCESSchool
  // as "No Data" (not a school); a handful of State Board of Education
  // charters report NCESDist as "No Data" instead. Either way, there's no
  // valid 12-digit nces_id to build, so these are skipped rather than
  // guessed at.
  if (!/^[0-9]{7}$/.test(distId) || !/^[0-9]{5}$/.test(schoolId)) {
    skippedNoSchoolId++;
    continue;
  }

  if (!name || name === 'No Data') {
    skippedNoName++;
    continue;
  }

  const ncesId = distId + schoolId;
  if (seenIds.has(ncesId)) {
    skippedDuplicate++;
    continue;
  }
  seenIds.add(ncesId);

  rows.push({
    ncesId,
    name,
    city: fields[col.City],
    state: fields[col.State],
    district: fields[col.District],
  });
}

// Deterministic output: sort by nces_id (not file order), so re-running this
// script against an unchanged input always regenerates a byte-identical file.
rows.sort((a, b) => (a.ncesId < b.ncesId ? -1 : a.ncesId > b.ncesId ? 1 : 0));

const headerComment = `-- School Directory seed — California public schools (full state).
-- Generated by scripts/import_ca_schools.js from the California Department
-- of Education's "Public Schools and Districts" directory (pubschls.txt):
--   https://www.cde.ca.gov/schooldirectory/report?rid=dl1&tp=txt
--
-- Generated at: ${new Date().toISOString()}
-- Source rows read: ${lines.length - 1}
-- Active school-level rows kept: ${rows.length}
-- Skipped — not Active (Closed/Merged/Pending): ${skippedNotActive}
-- Skipped — no valid school-level NCES id (district/county-office rows, or
--   missing NCESDist): ${skippedNoSchoolId}
-- Skipped — missing school name: ${skippedNoName}
-- Skipped — duplicate nces_id: ${skippedDuplicate}
--
-- Public schools only — this source file never includes private schools.
-- nces_id = NCESDist (7 digits) + NCESSchool (5 digits), the same format
-- already used by schools_seed_ca_fullerton_juhsd.sql, so those 8 existing
-- rows upsert in place below rather than duplicating.
--
-- Idempotent: keyed on nces_id (unique per schools_directory_schema.sql).
-- Re-running this file (or regenerating it from a fresh pubschls.txt and
-- running the new version) only ever inserts new schools or updates existing
-- ones by nces_id — never duplicates a row. A school that later closes is
-- simply absent from a future regeneration; this file does not delete rows,
-- so it would remain in the directory until a separate cleanup pass, if any
-- is ever built.
-- Does NOT touch profiles.school_name or profiles.school_id.
`;

const output = [headerComment];

for (let i = 0; i < rows.length; i += BATCH_SIZE) {
  const batch = rows.slice(i, i + BATCH_SIZE);
  const values = batch
    .map(
      (r) =>
        `  (${sqlLiteral(r.name)}, ${sqlLiteral(r.city)}, ${sqlLiteral(r.state)}, 'US', ${sqlLiteral(r.district)}, '${r.ncesId}')`
    )
    .join(',\n');

  output.push(
    [
      'insert into public.schools (name, city, state, country, district, nces_id)',
      'values',
      values,
      'on conflict (nces_id) do update set',
      '  name = excluded.name,',
      '  city = excluded.city,',
      '  state = excluded.state,',
      '  country = excluded.country,',
      '  district = excluded.district;',
      '',
    ].join('\n')
  );
}

fs.writeFileSync(outputPath, output.join('\n'));

console.log(`Source rows read: ${lines.length - 1}`);
console.log(`Active school-level rows kept: ${rows.length}`);
console.log(`  skipped (not Active): ${skippedNotActive}`);
console.log(`  skipped (no valid school-level NCES id): ${skippedNoSchoolId}`);
console.log(`  skipped (missing name): ${skippedNoName}`);
console.log(`  skipped (duplicate nces_id): ${skippedDuplicate}`);
console.log(`Batches written: ${Math.ceil(rows.length / BATCH_SIZE)} (batch size ${BATCH_SIZE})`);
console.log(`Wrote ${outputPath}`);
